export const ROLES = {
  ADMIN: 'Admin',
  ASSET_MANAGER: 'AssetManager',
  DEPARTMENT_HEAD: 'DepartmentHead',
  EMPLOYEE: 'Employee',
};

export const PROMOTABLE_ROLES = [ROLES.DEPARTMENT_HEAD, ROLES.ASSET_MANAGER];

export const ERROR_CODES = {
  ALLOCATION_CONFLICT: 'ALLOCATION_CONFLICT',
  BOOKING_OVERLAP: 'BOOKING_OVERLAP',
  INVALID_STATUS_TRANSITION: 'INVALID_STATUS_TRANSITION',
  AUDIT_CYCLE_CLOSED: 'AUDIT_CYCLE_CLOSED',
};
